name: Minimal CI/CD

on: [push]

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
#          mongodb-version: '4.2'
#          mongodb-replica-set: test-rs
          mongodb-port: 27017
          mongodb-username: admin
          mongodb-password: password
          mongodb-db: mongo-db


      - name: ğŸªœ Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: ğŸ’¾ Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod +x ./gradlew
        run:  chmod +x ./gradlew

      - name: ğŸ•‹ TEST
        run: ./gradlew test

      - name: ğŸ“¹ Jacoco test report
        run: ./gradlew jacocoTestReport
      - name: ğŸ Test codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#          files: ./build/reports/jacoco/test/jacocoTestReport.xml # optional
          verbose: true
